apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: foxe03/backend
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/notes
---
